"use client";
import { useState } from "react";

// import Notification from "@/src/app/Components/Notification";
// import { getMainPageData } from "@/src/Business/GetMainPageData";
import { addNotification } from "./Components/Notification";

export default function Home() {
  const [notificationType, setNotificationType] = useState<"info" | "warning" | "error">("info");
  // const [data, setData] = useState([]);

  // useEffect(() => {
  //   async function fetchData() {
  //     const result = await getMainPageData();
  //     setData(result);
  //   }
  //   fetchData();
  // }, []);

  const handleAddNotification = () => {
    const text = `This is a ${notificationType} notification generated by the system.`;

    console.log(text);

    addNotification({
      message: text,
      title: "Title 1",
      type: notificationType
    });
  };

  return (
    <div>
      <div className="flex m-2 justify-between items-center">
        <select
          value={notificationType}
          onChange={(e) => setNotificationType(e.target.value as "info" | "warning" | "error")}
          className="border p-2 rounded text-gray-900 cursor-pointer"
        >
          <option value="info">Info</option>
          <option value="warning">Warning</option>
          <option value="error">Error</option>
        </select>
        <button onClick={handleAddNotification} className="border p-2 rounded">
          Add Notification
        </button>
      </div>
    </div>
  );
}
